size: 9
picture_size: "300x200"
size_user: 15
size_gravatar: 50
size_picture_comment: 40
size_picture_commentting: 60
size_book: 6
limit_book: 4
limit_review: 10
relation:
  following: "following"
  followers: "followers"
btn:
  btn_favorite: "btn btn-favorite "
  btn_default: "btn-default"
  btn_success: "btn-success"
